# dataset and model files
release_files:
  preprocessed_dataset.zip: 
    url: https://www.xilinx.com/bin/public/openDownload?filename=preprocessed_dataset.zip
    extract_path: .
    md5_digit: 6a1afd3689154d18aaa2f4c3f0d7b5d3
  model.zip: 
    url: https://www.xilinx.com/bin/public/openDownload?filename=whisper_models_v6_v9.zip
    extract_path: .
    md5_digit: afe765d34d4a117ce8772c898266f818
  tvm-0.8.dev0+aie.0.2.4.tar.gz:
    url: https://www.xilinx.com/bin/public/openDownload?filename=tvm-0.8.dev-aie.0.2.4.tar.gz
    extract_path: false
    md5_digit: 8e5b99529e98e5767ebd5d3a6c253a49
  
